// Deterministic marketing layouts. Real app screenshots remain embedded intact.
const fs=require('fs'); const path=require('path');
const runtime='/Users/khatruong/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(runtime+'/playwright');
const root=path.resolve(__dirname,'..');
const data=(p,m='image/png')=>`data:${m};base64,${fs.readFileSync(p).toString('base64')}`;
const mascot=data(path.resolve(root,'../../../design/branding/budgie-mark.png'));
const logo=data(path.resolve(root,'../../Budgie/Resources/Assets.xcassets/logo.imageset/logo@3x.png'));
const font=data(path.resolve(root,'../../Budgie/Resources/Fonts/Gabarito-Regular.ttf'),'font/ttf');
const bold=data(path.resolve(root,'../../Budgie/Resources/Fonts/Gabarito-Bold.ttf'),'font/ttf');
const screen=n=>data(path.join(root,'raw',n+'.png'));
const brand=(light=false,size=62)=>`<div class="brand" style="font-size:${size}px"><img src="${logo}">Budgie</div>`;
const phone=(n,w,x,y)=>`<div class="phone" style="width:${w}px;left:${x}px;top:${y}px"><div class="display"><img src="${screen(n)}"><div class="island"></div></div></div>`;
const css=`@font-face{font-family:Gabarito;src:url('${font}')}@font-face{font-family:Gabarito;src:url('${bold}');font-weight:700}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:#07090D;font-family:Gabarito;color:#EEF1F5}.art{position:relative;overflow:hidden;width:100%;height:100%}.brand{display:flex;align-items:center;gap:18px;font-weight:700;letter-spacing:-2px}.brand img{width:1em;height:1em;object-fit:contain}.phone{position:absolute;background:linear-gradient(140deg,#606570,#1b1e24 35%,#434952 70%,#12151b);padding:14px;border-radius:100px;box-shadow:0 30px 100px #0009,inset 0 0 0 2px #b2bdcb55}.display{position:relative;overflow:hidden;border-radius:86px;background:#07090D}.display>img{width:100%;height:auto;display:block}.island{position:absolute;top:1.55%;left:36%;width:28%;height:3.3%;background:#000;border-radius:80px;box-shadow:inset 0 0 0 1px #181818}.eyebrow{font-size:29px;letter-spacing:5px;font-weight:700;color:#9AA3B2;text-transform:uppercase}h1{font-size:98px;line-height:1.035;letter-spacing:-3px;margin:0;font-weight:700}p{font-size:38px;line-height:1.3;color:#B5BFCE;margin:0}.accent{color:var(--accent,#5EE6B0)}.halo{position:absolute;width:1450px;height:1450px;border-radius:50%;background:radial-gradient(circle,var(--accent) 0%,transparent 67%);opacity:.12;left:0;top:1040px}.light{background:#F3EFE6;color:#1A1A17}.light .eyebrow,.light p{color:#5C584F}.light .accent{color:#1D6646}.bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.creative-copy{position:absolute}.creative-copy h1{font-size:194px;line-height:1.04;letter-spacing:-6px}.creative-copy p{font-size:72px;color:#B5BFCE}.header-brand{position:absolute;left:220px;top:190px}.header-brand .brand{gap:30px}.header-brand .brand img{width:120px;height:120px}`;
function html(body,cls='',style=''){return `<!doctype html><html><meta charset="utf-8"><style>${css}</style><body class="${cls}"><div class="art" style="${style}">${body}</div></body></html>`;}
const shots=[
['01-home-dark','YOUR EVERYDAY MONEY','Feel good about<br><span class="accent">your money.</span>','Income, spending, and what’s safe to spend.','#5EE6B0'],
['02-spending-dark','SPENDING, IN FOCUS','Know where<br><span class="accent">your money goes.</span>','A clear view of every category.','#B3ADFF'],
['03-goals-dark','MAKE ROOM FOR WHAT MATTERS','Small steps.<br><span class="accent">Bigger goals.</span>','Set a target. Watch your progress.','#5EE6B0'],
['04-worth-dark','THE BIGGER PICTURE','See how far<br><span class="accent">you’ve come.</span>','Track your assets, debts, and net worth.','#B3ADFF'],
['05-flow-dark','FIND YOUR FINANCIAL RHYTHM','Turn your numbers<br><span class="accent">into perspective.</span>','Spot the trends in your cash flow.','#FF8B7B'],
['06-home-light','PAPER OR MIDNIGHT','A fresh look.<br><span class="accent">Your kind of calm.</span>','Choose the theme that feels like you.','#1D6646'],
['07-recurring-dark','KEEP THE ROUTINE SIMPLE','Bills and paydays.<br><span class="accent">On repeat.</span>','Keep recurring transactions together.','#FFC861']
];
const assets=[];
for(const [n,label,title,sub,color]of shots){assets.push({name:n,w:1206,h:2622,folder:'screenshots',html:html(`<div class="halo"></div><div style="position:absolute;left:80px;top:70px">${brand(n.includes('light'))}</div><div class="eyebrow" style="position:absolute;left:80px;top:193px">${label}</div><h1 style="position:absolute;left:80px;top:250px">${title}</h1><p style="position:absolute;left:80px;top:476px">${sub}</p>${phone(n,938,134,588)}`,n.includes('light')?'light':'',`--accent:${color}`)});}
assets.push({name:'header-3840x1646',w:3840,h:1646,folder:'creative',html:html(`<div class="header-brand">${brand(false,110)}</div><div class="creative-copy" style="left:220px;top:475px"><h1>Your money.<br><span class="accent">A little clearer.</span></h1><p style="margin-top:85px">Budgets. Goals. A bigger picture.</p></div><img alt="Budgie blue bird saving a coin" src="${mascot}" style="position:absolute;left:2050px;top:370px;width:860px;height:860px;object-fit:contain">${phone('01-home-dark',630,2960,140)}`, '', '--accent:#C3ADFF')});
assets.push({name:'search-results-3840x2560',w:3840,h:2560,folder:'creative',html:html(`<div style="position:absolute;left:240px;top:280px">${brand(false,116)}</div><div class="creative-copy" style="left:240px;top:775px"><h1>Personal finance.<br><span class="accent">Made personal.</span></h1><p style="margin-top:110px;line-height:1.4">Track spending. Build your goals.<br>See your money clearly.</p></div>${phone('01-home-dark',1020,2590,180)}`)});
assets.push({name:'search-results-goals-3840x2560',w:3840,h:2560,folder:'creative',html:html(`<div style="position:absolute;left:240px;top:280px">${brand(false,116)}</div><div class="creative-copy" style="left:240px;top:775px"><h1>Make room for<br><span class="accent">your next chapter.</span></h1><p style="margin-top:110px;line-height:1.4">Savings goals, spending, and net worth.<br>All together in Budgie.</p></div>${phone('03-goals-dark',1020,2590,180)}`, '', '--accent:#B3ADFF')});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--disable-gpu']});
 for(const a of assets){const out=path.join(root,a.folder,a.name+'.png');fs.writeFileSync(path.join(__dirname,a.name+'.html'),a.html);const page=await browser.newPage({viewport:{width:a.w,height:a.h},deviceScaleFactor:1});await page.setContent(a.html);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:out,omitBackground:false});await page.close();console.log(a.name,a.w+'x'+a.h);}
 const thumbs=assets.map(a=>`<div><img src="${data(path.join(root,a.folder,a.name+'.png'))}"><p>${a.name}</p></div>`).join('');
 const sheet=`<!doctype html><html><style>body{margin:0;background:#e6e7ec;padding:28px;font:15px Arial}.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:16px}.grid img{width:100%;border-radius:10px}p{margin:8px 0 20px}.grid div:nth-child(n+8){grid-column:span 2}</style><div class="grid">${thumbs}</div></html>`;
 const page=await browser.newPage({viewport:{width:1800,height:1350},deviceScaleFactor:1});await page.setContent(sheet);await page.screenshot({path:path.join(root,'preview.png'),fullPage:true});await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
