name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Trigger the action on push to main branch

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get
      working-directory: budget_app  # Navigate into budget_app directory

    - name: Build IPA
      run: flutter build ipa
      working-directory: budget_app  # Navigate into budget_app directory
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myApp
        path: budget_app/build/ios/ipa/myApp.ipa  # Adjusted path
