name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'  

    - name: Install Dependencies
      run: flutter pub get
      working-directory: budget_app

    - name: Clean
      run: flutter clean
      working-directory: budget_app

    - name: Build IPA
      run: flutter build ipa
      working-directory: budget_app
      
    # Example of using GitHub secret in a Flutter app as an environment variable
    - name: Use Secret as Environment Variable
      run: |
        echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" > .env
        flutter run
